import { Poppins } from 'next/font/google';
import "./globals.css";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap', // 'swap' ensures that text is visible while the font is loading
  variable: '--font-poppins', // Assign a CSS variable
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] // Specify all weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
